server:
 applicationConnectors:
   - type: http
     port: 9090
 adminConnectors:
   - type: http
     port: 9091

logging:
 level: INFO
 appenders:
     - type: file
       currentLogFilename: /dashbase/prometheus-proxy-framework/logs/prometheus.log
       archive: true
       archivedLogFilenamePattern: /dashbase/prometheus-proxy-framework/logs/prometheus-%d.log
       archivedFileCount: 9
       timeZone: UTC
     - type: console