server:
 applicationConnectors:
   - type: http
     port: 9090
 adminConnectors:
   - type: http
     port: 9091

logging:
 level: INFO
 appenders:
     - type: file
       currentLogFilename: x.log
       archive: true
       archivedLogFilenamePattern: x-%d.log
       archivedFileCount: 9
       timeZone: UTC
     - type: console