package token;

public enum ItemType{
    itemError,
    itemEOF,
    itemComment,
    itemIdentifier,
    itemMetricIdentifier,
    itemLeftParen,
    itemRightParen,
    itemLeftBrace,
    itemRightBrace,
    itemLeftBracket,
    itemRightBracket,
    itemComma,
    itemAssign,
    itemSemicolon,
    itemString,
    itemNumber,
    itemDuration,
    itemBlank,
    itemTimes,

    operatorsStart,
    // Operators.
    itemSUB,
    itemADD,
    itemMUL,
    itemMOD,
    itemDIV,
    itemLAND,
    itemLOR,
    itemLUnless,
    itemEQL,
    itemNEQ,
    itemLTE,
    itemLSS,
    itemGTE,
    itemGTR,
    itemEQLRegex,
    itemNEQRegex,
    itemPOW,
    operatorsEnd,
    aggregatorsStart,
    // Aggregators.
    itemAvg,
    itemCount,
    itemSum,
    itemMin,
    itemMax,
    itemStddev,
    itemStdvar,
    itemTopK,
    itemBottomK,
    itemCountValues,
    itemQuantile,
    aggregatorsEnd,

    keywordsStart,
    // Keywords.
    itemAlert,
    itemIf,
    itemFor,
    itemLabels,
    itemAnnotations,
    itemOffset,
    itemBy,
    itemWithout,
    itemOn,
    itemIgnoring,
    itemGroupLeft,
    itemGroupRight,
    itemBool,
    keywordsEnd;
}
